on:
  pull_request:  
    #don't re-run if changes are just "cosmetic"
    paths-ignore:
      - 'README*'
      - 'LICENSE*'
      - 'docs/**'
      - 'doc/**'
      - 'man/**'
      - 'vignettes/**'
      - 'CITATION.cff'
      - 'NEWS.md'

name: run_workflow.yml

jobs:
  states:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        state: ["RI", "DE"]
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::. 
      
      - name: Generate state parquet
        run: Rscript -e 'source("scripts/state-parquet.R")'
        env:
          STATE: ${{ matrix.state }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.state }}
          path: fia/parquet/*
